# SPDX-License-Identifier: GPL-2.0
#Platform Support
snd-soc-loongson-i2s-pci-objs := loongson_i2s_pci.o loongson_i2s.o loongson_dma.o
obj-$(CONFIG_SND_SOC_LOONGSON_I2S_PCI) += snd-soc-loongson-i2s-pci.o
obj-$(CONFIG_SND_LS_I2S)   += ls-i2s.o
obj-$(CONFIG_SND_LS_PCM)   += ls-pcm.o
obj-$(CONFIG_SND_LS_SOUND) += ls-sound.o

#Machine Support
snd-soc-loongson-card-objs := loongson_card.o
obj-$(CONFIG_SND_SOC_LOONGSON_CARD) += snd-soc-loongson-card.o
